'use client';

import { Navigation } from '@/components/shared/navigation';
import { Footer } from '@/components/shared/footer';
import { HeroSection } from '@/components/shared/hero-section';
import { FadeInUp } from '@/components/animations/fade-in-up';

export default function PrivacyPage() {
    return (
        <main className="min-h-screen bg-background">
            <Navigation />

            <HeroSection
                badgeText="Legal"
                title="Privacy Policy"
                description="Last updated: February 12, 2026"
                backgroundVariant="gradient"
            />

            <section className="py-16 md:py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
                <FadeInUp>
                    <div className="glass-effect p-8 md:p-12 rounded-3xl border border-white/10 prose prose-invert prose-cyan max-w-none">
                        <p className="text-slate-400 leading-relaxed mb-6">
                            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        </p>
                        <p className="text-slate-400 leading-relaxed mb-12">
                            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                        </p>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Interpretation and Definitions</h2>
                        <h3 className="text-cyan-400 mt-8 mb-4">Interpretation</h3>
                        <p className="text-slate-400 leading-relaxed mb-6">
                            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </p>

                        <h3 className="text-cyan-400 mt-8 mb-4">Definitions</h3>
                        <p className="text-slate-400 leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
                        <ul className="list-disc pl-6 space-y-4 text-slate-400 mb-12">
                            <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                            <li><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to VisionSpeak AI, 200 Park Ave, New York, NY 10166, United States.</li>
                            <li><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><strong className="text-white">Country</strong> refers to: New York, United States</li>
                            <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                            <li><strong className="text-white">Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
                            <li><strong className="text-white">Service</strong> refers to the Website.</li>
                            <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                            <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li><strong className="text-white">Website</strong> refers to VisionSpeak AI, accessible from <a href="https://visionspeakai.com" className="text-cyan-400 hover:underline">https://visionspeakai.com</a>.</li>
                            <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Collecting and Using Your Personal Data</h2>
                        <h3 className="text-cyan-400 mt-8 mb-4">Types of Data Collected</h3>

                        <h4 className="text-white mt-6 mb-3 font-bold">Personal Data</h4>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-slate-400 mb-8">
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Phone number</li>
                        </ul>

                        <h4 className="text-white mt-6 mb-3 font-bold">Usage Data</h4>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            Usage Data is collected automatically when using the Service.
                        </p>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        </p>
                        <p className="text-slate-400 leading-relaxed mb-8">
                            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                        </p>

                        <h4 className="text-white mt-6 mb-3 font-bold">Tracking Technologies and Cookies</h4>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                        </p>
                        <ul className="list-disc pl-6 space-y-4 text-slate-400 mb-6">
                            <li><strong className="text-white">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                            <li><strong className="text-white">Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                        </ul>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                        </p>
                        <p className="text-slate-400 leading-relaxed mb-6">
                            Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool.
                        </p>

                        <h3 className="text-cyan-400 mt-8 mb-4">Use of Your Personal Data</h3>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            The Company may use Personal Data for the following purposes:
                        </p>
                        <ul className="list-disc pl-6 space-y-4 text-slate-400 mb-12">
                            <li><strong className="text-white">To provide and maintain our Service</strong></li>
                            <li><strong className="text-white">To manage Your Account:</strong> manage User registration</li>
                            <li><strong className="text-white">For the performance of a contract:</strong> compliance with purchase contracts</li>
                            <li><strong className="text-white">To contact You:</strong> By email, phone, SMS, or push notifications</li>
                            <li><strong className="text-white">To provide You</strong> with news, special offers and general information</li>
                            <li><strong className="text-white">To manage Your requests:</strong> To attend and manage Your requests to Us</li>
                        </ul>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Retention of Your Personal Data</h2>
                        <p className="text-slate-400 leading-relaxed mb-6">
                            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply specific retention periods for different categories of data:
                        </p>
                        <ul className="list-disc pl-6 space-y-4 text-slate-400 mb-8">
                            <li><strong className="text-white">User Accounts:</strong> duration of relationship plus up to 24 months</li>
                            <li><strong className="text-white">Support Data:</strong> up to 24 months from ticket closure</li>
                            <li><strong className="text-white">Website Analytics:</strong> up to 24 months from collection</li>
                            <li><strong className="text-white">Server Logs:</strong> up to 24 months for security</li>
                        </ul>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Disclosure of Your Personal Data</h2>
                        <h4 className="text-white mt-6 mb-3 font-bold">Business Transactions</h4>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                        </p>

                        <h4 className="text-white mt-6 mb-3 font-bold">Law enforcement</h4>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                        </p>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Children's Privacy</h2>
                        <p className="text-slate-400 leading-relaxed mb-6">
                            Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                        </p>

                        <h2 className="text-white mt-12 mb-6 border-b border-white/10 pb-2">Contact Us</h2>
                        <p className="text-slate-400 leading-relaxed mb-6">
                            If you have any questions about this Privacy Policy, You can contact us:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-slate-400">
                            <li>By email: support@visionspeakai.com</li>
                            <li>By visiting this page on our website: <a href="https://visionspeakai.com/contact" className="text-cyan-400 hover:underline">https://visionspeakai.com/contact</a></li>
                        </ul>
                    </div>
                </FadeInUp>
            </section>

            <Footer />
        </main>
    );
}
